version: '3.8'

services:
  app:
    container_name: template-api
    build:
      context: ./app
      target: dev
    ports:
      - "9000:${SERVER_PORT}"
      - "2345:2345"
    volumes:
      - ./:/src
    env_file: .env
    depends_on: 
      db: 
        condition: service_healthy
  db:
    container_name: template-db
    image: mysql:8.0
    ports:
      - "33306:${MYSQL_PORT}"
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=UTC
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
      test: mysqladmin ping -h 127.0.01 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: