name: deploy

on:
  workflow_dispatch:

env:
  APP_ENV: dev
  SERVICE_NAME: template-service
  AWS_ACCOUNT_ID: "878423098926"
  AWS_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.APP_ENV }}-github-actions-role

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/setup-buildx-action@v3

      - name: Build Push to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ENV }}-${{ env.SERVICE_NAME }}-api:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ENV }}-${{ env.SERVICE_NAME }}-api:latest
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ENV }}-${{ env.SERVICE_NAME }}-api:cache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ENV }}-${{ env.SERVICE_NAME }}-api:cache,mode=max,image-manifest=true

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.APP_ENV }}-github-actions-role

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Combine Task Definition
        # あとで消す
        # run: |
        # cat task-definition/${{ env.APP_ENV }}/container-definitions/*.json | jq -s > task-definition/${{ env.APP_ENV }}/container-definitions.json
        # jq '.containerDefinitions = input' task-definition/${{ env.APP_ENV }}/task-definition.json task-definition/${{ env.APP_ENV }}/container-definitions.json > ./task-definitions.json
        run: |
          jq -s '.[0] * {containerDefinitions: .[1]}' ecs-task-definition/${{ env.APP_ENV }}/base-task-definition.json ecs-task-definition/${{ env.APP_ENV }}/container-definition.json > task-definitions.json

      - name: mod ecs task
        id: render-app-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # task-definitions.json内のimageタグの内容はなんでもよい。以下のimageに置換される。
          task-definition: task-definitions.json
          container-name: dev-api
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_ENV }}-${{ env.SERVICE_NAME }}-api:${{ github.sha }}

      - name: deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-app-container.outputs.task-definition }}
          service: ${{ env.APP_ENV }}-service
          cluster: ${{ env.APP_ENV }}-cluster
